#pragma once

enum ReturnCodes
{
    SUCCESS,
    FAILURE,
    ARGUMENT_HELP,
    ARGUMENT_CHECK_FAILURE,
    NETWORK_ANALYSER_CREATION_FAILURE,
    MESSAGE_PUBLISHER_CREATION_FAILURE,
    MESSAGE_PUBLISHER_TIMEOUT
};
